language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: WHnGrS+txWfYbb3o+TAoZH17FbiCCo8Wbi2MJaG8kR1a0PqsnbBw24t5ktUKYWyqnWrYecMIS4TiHpO64Vnqkfcu6uqrjLEzTcdFGjoPC4/LTwnV+OYviICUS7Gc+d4cuOxNXJJLZqFc3cccdxpyeEz041JvwrnOYZCPQPMSSUBzVCUslhpZ9SVB8GecvvE2fsq576GRNwhjVUaewAgtw+6ruzmvgfcmLa2238S9oFuPJqEp6xrhAMZrVLySj7PwWbcnAEZYEzRSRnEZQ9TpjERiIbkjdhpWFZ7heMb/V4LQSn/ThavBBs7NvY0mblSV9F26r5fM9FVKhpWk8XzolM5OVOVNJ0K3dPpye9pVXCFGNNuFnclOs7fPRIppg3YdseXCjhMoBJS1bdf5/MfVb6ycibUljeRLh5G3hbrtB/yQ14Rgcq6fqJQIuzVnQcXPZXQL9qyKPiH43QPBXy3NGbvDl938TBrH35fTyJ0Agh+BIIQJO1N9gy9envzLgh620hHbIRivL57GoqzCSZauu4ZNvnlsPXVCr/iSJ1G4j97lmoVrMHu7/AGPfQ4zJxb5Rj4DsObyyUydj5JwSDEqwKdPt1oUMeRSK4xk79ahbQUfTOB6sXH3h0L5wxbuXp3AVaiTM/L6fshoVj3zniwjMVhTPFZZw3hoeUQ+p7HC9Xk=
  app: floating-eyrie-81076
  on:
    repo: aaronleebrooks/myWallet
